language: python
python:
    - "2.7"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libprotobuf-dev libzmq3-dev protobuf-compiler
    - sudo apt-get install -qq libbluetooth-dev bluez-tools bluez bluetooth
    - git submodule update --init --recursive
    - pip install -r requirements.txt
    - ./generate.sh
script: make coverage
